### ISSUE TITLE
Some keyboard shortcuts dont work

### ISSUE THREAD

**Issue by farmboy0** [Interrupt/systemshock#100]
I have a german keyboard with a german key map.
Some keyboard shortcuts are inaccessible to me.
All ALT shortcuts don't work.
All shortcuts from special characters like ? or ; or : don't work either because I need shift to access them.
I wager that most international keyboards will have this problem.

**Comment by donnierussellii** [comment]
The Alt modifier doesn't work because we need code to handle the Option key on Mac keyboards in sdl_events.c.

I am working on customizable hotkey bindings, which will get around this for now.

**Comment by donnierussellii** [comment]
Customizable key combinations and enabled ALT modifier in my PR #206
