### ISSUE TITLE
Windows release builds error on startup

### ISSUE THREAD

**Issue by Interrupt** [Interrupt/systemshock#102]
AppVeyor built releases fail on startup for me on Windows 10 with this error:

![error](https://user-images.githubusercontent.com/1374/42904929-6c6474c4-8a8b-11e8-928b-e3c121ad85d6.PNG)

**Comment by mrikola** [comment]
Looks like `libstdc++-6.dll` is the culprit, and I think it's because the Git installation we're pulling it from on AppVeyor is 64-bit and everything else is 32-bit. I wonder if there's another place we could look for it, as the MinGW installation doesn't seem to include it.

**Comment by Interrupt** [comment]
If worst comes to worst, we could include that binary in the repo.

**Comment by mrikola** [comment]
Okay, I did the "sensible" thing of running `dir libstdc++-6.dll /s` on AppVeyor, and it turns out.. the DLL is in the `C:\MinGW\bin` directory after all, the weird file name just made copying difficult inside the script.
