### ISSUE TITLE
Click-for-Options cursor is displayed instead of crosshair

### ISSUE THREAD

**Issue by inguin** [Interrupt/systemshock#110]
When enabling mouse look (hotkey 'F') while the mouse cursor is in the top left window corner, the mouse cursor does not change to a crosshair. The Click-for-Options cursor is displayed in the screen center.

**Comment by solidgriever** [comment]
I made a PR for a fix ... or a starting point for a real fix.

**Comment by inguin** [comment]
Works for me. Thanks!
