### ISSUE TITLE
Gamma correction slider

### ISSUE THREAD

**Issue by mrikola** [Interrupt/systemshock#117]
The slider has two settings: a bit dim at 0, and totally oversaturated anywhere above it.

![dim](https://user-images.githubusercontent.com/20069423/43305463-93336db6-9180-11e8-85dc-b710a80afc0d.png)
![bright](https://user-images.githubusercontent.com/20069423/43305467-97753a9e-9180-11e8-9664-d7d2484de114.png)

But whichever setting you pick, the actual game still looks like the default.

![actual](https://user-images.githubusercontent.com/20069423/43305498-ae708bae-9180-11e8-8395-f12bb1fada78.png)

**Comment by solidgriever** [comment]
![arhive](https://user-images.githubusercontent.com/5406932/43743261-be5384f8-99dd-11e8-8820-59e7b3683ba7.gif)
I had a look at that ... the slider is almost functioning but it still reverts to the default gamma value

**Comment by donnierussellii** [comment]
Gamma slider and gamma update in game loop fix in my PR #165.
