### ISSUE TITLE
Movies / Audiologs need a decoder

### ISSUE THREAD

**Issue by Interrupt** [Interrupt/systemshock#13]
The decoder for the movies in AFile seems to be missing from the sources. That will need to be re-implemented to get the cutscenes and audiologs to work again.

Thankfully @inkyblackness has a writeup of how one should be written: https://github.com/inkyblackness/ss-specs/blob/master/media/moviResources.md

**Comment by Interrupt** [comment]
We have the audio part of movies playing now thanks to @winterheart so that Audiologs work, next bit of work might be to revive the lower res movies used in the floppy version as those are much simpler bitmap sequences.

**Comment by Interrupt** [comment]
We have the missing functions now thanks to Axemelon over at the NightDive source port, the dissasembled and converted to C versions can be found here: 
[AFile-missing-code.zip](https://github.com/Interrupt/systemshock/files/2255438/AFile-missing-code.zip)

**Comment by JPLeBreton** [comment]
Can this be marked fixed now?

**Comment by Interrupt** [comment]
Yep! Closing.
