### ISSUE TITLE
[OpenGL] No stars in level 6 groves

### ISSUE THREAD

**Issue by inguin** [Interrupt/systemshock#136]
With the OpenGL renderer, the stars can't be seen through the ceiling windows in level 6 (and a few other places):
![screenshot_20180815_211209](https://user-images.githubusercontent.com/150479/44167947-dfe80780-a0cf-11e8-8991-eddf6f86dc0c.png)
![screenshot_20180815_211230](https://user-images.githubusercontent.com/150479/44167963-ec6c6000-a0cf-11e8-801f-8ade39f0317a.png)

**Comment by Interrupt** [comment]
Fixed in 8921588ce4dc1bb62e65c461f366176a7d742b29
