### ISSUE TITLE
[OpenGL] Weird star glitches at some places

### ISSUE THREAD

**Issue by inguin** [Interrupt/systemshock#137]
The OpenGL star rendering glitches in a few places. I can reliably reproduce it in a room a the beginning of level 2 (see [this savegame](https://github.com/Interrupt/systemshock/files/2291420/savgam00.zip)):

1. Open the door and walk slowly towards the window; the stars "zoom out" when crossing the doorstep.
2. Walk closer to the window; at some point the stars disappear.

**Comment by inguin** [comment]
All three coordinates of each star become very small at the point of the zoom, so there's probably a rounding issue somewhere. It works when using the screen coordinates of each point (sx/sy/0) instead of the 3D coordinates, but I'm not sure how `g3_project_point()` can do a better job than OpenGL.

The second issue is still a mystery.

**Comment by Interrupt** [comment]
Interesting find! For me the stars even disappear at some spots using the sx / sy coordinates. Switching back to the Software renderer in those spots shows the stars, so it's even stranger.

**Comment by Interrupt** [comment]
https://github.com/Interrupt/systemshock/pull/142 fixes some star rendering issues, but they still disappear sometimes.
