### ISSUE TITLE
Cutscenes are missing subtitles

### ISSUE THREAD

**Issue by Interrupt** [Interrupt/systemshock#139]
The death cutscene should show that "They find your body and give it new life" text. This is probably stored in text blocks in the highres cutscenes.

**Comment by donnierussellii** [comment]
Added in my PR #180, but color is wrong.

**Comment by Interrupt** [comment]
Think there was some known palette color they were using for drawing those?

**Comment by donnierussellii** [comment]
Yes, it was color 255. It has the correct rgb for each frame. But drawing with 255 produced black for me.

**Comment by Interrupt** [comment]
It might be that it's drawing transparently then, in some drawing modes that color is used for masking.
