### ISSUE TITLE
[Feature Request] Grenade hotkey

### ISSUE THREAD

**Issue by voodoo47** [Interrupt/systemshock#150]
A grenade hotkey (first press to attach the grenade to the cursor, second press to arm it, ideally not turning mouselook off while doing this) would be a godsend.

**Comment by donnierussellii** [comment]
There is a hotkey to do that, alt+quote. Ctrl+quote selects the type of grenade. But Alt is not currently working--we need code to properly handle the Mac Option modifier.

My next PR will allow customizable hotkey binding, which will work around this.

**Comment by voodoo47** [comment]
would be great if the hotkey played nice with mouselook, as mentioned.

**Comment by donnierussellii** [comment]
The grenade hotkeys don't turn off mouselook in my current build.
