### ISSUE TITLE
[Feature Request] improved player physics/movement

### ISSUE THREAD

**Issue by voodoo47** [Interrupt/systemshock#155]
anything that would make the player movement/physics feel less like poking around a big ball of rubber bands with a pool cue would be very, very welcome.

**Comment by Interrupt** [comment]
Shockolate is aiming to be pretty close to vanilla in terms of gameplay, there should probably be a discussion around how far we want to go when changing base things like the player physics. My current line of thinking is that we should leave it as is, since the physics system is pretty unique.

**Comment by voodoo47** [comment]
unique doesn't necessarily mean good. also, not saying that the vanilla physics should be straight out replaced - the new physics would be an enhancement, and those should always be optional.

potato physics ON/OFF

**Comment by Interrupt** [comment]
For things like this that change the base gameplay the best approach might be to try to expose some of the hardcoded gameplay variables to config values that could be packaged with a mod. Changing them in the base game seems like a step too far, but opening them up to tinkering seems like a good thing.
