### ISSUE TITLE
the crosshair doesn't use the correct weapon color scheme in certain situations

### ISSUE THREAD

**Issue by voodoo47** [Interrupt/systemshock#156]
picking up and equipping your first pipe will not change the crosshair color to the melee color scheme, for example, saving and loading will also reset it to the default red one, no matter what weapon type is equipped. quite sure there are some more situations where the crosshair will just reset to the default color scheme, I'll post here in case I find more stuff. this is a really old vanilla bug btw, would love to see it gone.

**Comment by donnierussellii** [comment]
We need a function like change_selected_weapon(), but it only needs to look at the current active weapon and change the motion cursors' color.

Then call this at the end of:

weapons_add_func()
weapon_drop_func()
screen_start()
fullscreen_start() <----- a screen_draw() should also be here, as in screen_start()

There may be other places it's needed, but I think this is enough.

**Comment by donnierussellii** [comment]
I finished the changes. In the process I fixed a bug that caused stack corruption and a crash related to the way cursor bitmaps are allocated when changing resolutions. One problem function in particular was incredible.
