### ISSUE TITLE
Re the comments in src/stubs/Carbon/{Carbon.h,carbon_stubs.c}

### ISSUE THREAD

**Issue by Kristine1975** [Interrupt/systemshock#158]
Not really an issue, just some notes on the comments in the above files:

`Carbon.h`:

> [// pascal is used for some functions from Carbon/MacOS that use Pascal linkage or sth](https://github.com/Interrupt/systemshock/blob/31f2e31a4543f77c6fa0bf4354bb4370b05eb805/src/stubs/Carbon/Carbon.h#L9)
> // whatever, this define makes the compiler shut up for now :-P

The original MacOS was written in Pascal which has different calling conventions than C, so this was needed for C to interface with the OS. Definitely not needed anymore.

> [typedef void* CGrafPtr; // whatever this is?](https://github.com/Interrupt/systemshock/blob/31f2e31a4543f77c6fa0bf4354bb4370b05eb805/src/stubs/Carbon/Carbon.h#L19)

A pointer to a [CGrafPort](http://mirror.informatimago.com/next/developer.apple.com/documentation/QuickTime/APIREF/SOURCESIV/cgrafport.htm), part of the original MacOS's drawing framework.

>[typedef Handle PixMapHandle; // whatever this is..](https://github.com/Interrupt/systemshock/blob/31f2e31a4543f77c6fa0bf4354bb4370b05eb805/src/stubs/Carbon/Carbon.h#L21)

A handle (movable pointer, used to avoid memory fragmentation) to a [PixMap](http://mirror.informatimago.com/next/developer.apple.com/documentation/QuickTime/APIREF/SOURCESIV/pixmap.htm), a pixel image.

> typedef Handle CTabHandle; // ...

A handle to a [ColorTable](http://mirror.informatimago.com/next/developer.apple.com/documentation/QuickTime/APIREF/SOURCESIV/colortable.htm), a color table (d'uh) used with indexed images.

>[struct FSSpec](https://github.com/Interrupt/systemshock/blob/31f2e31a4543f77c6fa0bf4354bb4370b05eb805/src/stubs/Carbon/Carbon.h#L38)

A [file path](http://mirror.informatimago.com/next/developer.apple.com/documentation/Carbon/Reference/File_Manager/file_manager/data_type_40.html) in the original MacOS: By storing the volume number, the ID of the directory, and the file name, files could be moved without a path to it becoming invalid.

>[// TODO: just eliminate all calls to this?](https://github.com/Interrupt/systemshock/blob/31f2e31a4543f77c6fa0bf4354bb4370b05eb805/src/stubs/Carbon/Carbon.h#L105)

This returns [e.g. why the last memory allocation failed](http://mirror.informatimago.com/next/developer.apple.com/documentation/Carbon/Reference/Memory_Manager/memory_mgr_ref/function_group_4.html#//apple_ref/c/func/MemError). It should be ok to just remove it.

`carbon_stubs.c`:

>[GetResource](https://github.com/Interrupt/systemshock/blob/31f2e31a4543f77c6fa0bf4354bb4370b05eb805/src/stubs/Carbon/carbon_stubs.c#L16)

Loaded a resource (structured data) from a resource file (essentially a database of structured data). For some reason the MacOS port of System Shock didn't use the original data files, but converted them to MacOS resource files and then used the OS to load textures etc. So it's not needed anymore when using the original System Shock data files.

>[SetPort](https://github.com/Interrupt/systemshock/blob/31f2e31a4543f77c6fa0bf4354bb4370b05eb805/src/stubs/Carbon/carbon_stubs.c#L73)

Sets the CGrafPort (see above) that is used by drawing functions. Indeed not needed anymore after switching to SDL.

**Comment by Interrupt** [comment]
Thanks for the background on all of this! Now that things are running reliably, we could start going through and removing all of the Mac specific references.
