### ISSUE TITLE
Terrain elevator sound never stops

### ISSUE THREAD

**Issue by donnierussellii** [Interrupt/systemshock#166]
There is a bug with terrain elevators (not inter-level elevators), such that if you push a switch to raise/lower it, then push it again while the sound is still playing, the sound will never stop. This likely is related to what's going on in set_sample_pan_gain().

**Comment by farmboy0** [comment]
you would be better off putting everything in separate PRs.

**Comment by donnierussellii** [comment]
Good advice--I've never made a PR before.

**Comment by Interrupt** [comment]
@farmboy0 is right, in Git it's cheap and easy to make a branch so making a new branch for each fix off of master is usually preferable since it makes reviewing changes easy and bite size. This is fine for now though, just to good to keep in mind in the future.
