### ISSUE TITLE
Clicking continue on main menu crashes game

### ISSUE THREAD

**Issue by donnierussellii** [Interrupt/systemshock#175]
Start new game with no saved savgam##.dat files, save and quit game, run game again and click continue.

**Comment by donnierussellii** [comment]
Fix in my PR #176.

**Comment by Interrupt** [comment]
I think this should open the savegames list and let the user pick a save, at least in my testing.

**Comment by donnierussellii** [comment]
Okay, finally found the crash. That was a super sneaky one. PR #182.
