### ISSUE TITLE
Crash on level 6 G1

### ISSUE THREAD

**Issue by acd2001** [Interrupt/systemshock#178]
Clicking on CONTROL PEDESTAL crash shocolate
![level6-g1](https://user-images.githubusercontent.com/43091220/45254166-184bd000-b374-11e8-808b-4c8b93d33fef.jpg)
[savgam01.zip](https://github.com/Interrupt/systemshock/files/2363297/savgam01.zip)

**Comment by donnierussellii** [comment]
Thanks for the save!

Program received signal SIGFPE, Arithmetic exception.
0x00469a19 in trap_hack_func ()
(gdb) backtrace
#0  0x00469a19 in trap_hack_func ()
#1  0x0046a620 in grind_trap ()
#2  0x0046a91d in trap_activate ()
#3  0x00469c2b in do_multi_stuff ()
#4  0x00458011 in trap_event_handler ()
#5  0x00458a58 in schedule_run ()
#6  0x00458ad8 in run_schedules ()
#7  0x004101f7 in update_state ()
#8  0x0040d9ba in game_loop ()
#9  0x00421f33 in mainloop ()
#10 0x00401cea in SDL_main ()
#11 0x0050fa47 in main_utf8 ()
#12 0x0050faf8 in main_getcmdline ()
#13 0x0050fbfb in WinMain@16 ()
#14 0x00519434 in main ()
