### ISSUE TITLE
No free filenum when playing intro cutscene

### ISSUE THREAD

**Issue by donnierussellii** [Interrupt/systemshock#191]
Play intro and death cutscenes multiple times until this warning appears and cutscene no longer plays:
resfile.c:116: ResOpenResFile: no free filenum for: res/data/svgaintr.res

Then when clicking Continue game crashes.

**Comment by Interrupt** [comment]
Are we forgetting to drop the resource when the cutscene is done playing?

**Comment by donnierussellii** [comment]
Fix in my PR #194
