### ISSUE TITLE
Shodan detection crash

### ISSUE THREAD

**Issue by acd2001** [Interrupt/systemshock#203]
In cyberspace, when time is over and Shodan detection is imminent, shockolate crash badly

**Comment by donnierussellii** [comment]
Program received signal SIGFPE, Arithmetic exception.
0x0049c191 in show_obj ()
(gdb) backtrace
#0  0x0049c191 in show_obj ()
#1  0x0049cea7 in render_sorted_objs ()
#2  0x00496751 in render_parse_obj ()
#3  0x0040ddac in fr_draw_tile ()
#4  0x004979ff in fr_pipe_go_3 ()
#5  0x004963a6 in fr_rend ()
#6  0x00456aa3 in render_run ()
#7  0x004105a5 in game_loop ()
#8  0x0042452b in mainloop ()
#9  0x00401cc4 in SDL_main ()
#10 0x005307a7 in main_utf8 ()
#11 0x00530858 in main_getcmdline ()
#12 0x0053095b in WinMain@16 ()
#13 0x0055d694 in main ()
