### ISSUE TITLE
"Reviving" text in intro screen have black color instead red

### ISSUE THREAD

**Issue by winterheart** [Interrupt/systemshock#217]
"Reviving" text at the end of intro screen have black color instead red:
![ss01](https://user-images.githubusercontent.com/81112/45973344-de9ee880-c046-11e8-8224-a67f779e7f15.png)

And seems this last sequnce runs little shorter than should be.

**Comment by donnierussellii** [comment]
I understand the deal with 255 being black, will remove hacks in future PR. Also do a fade to black at end.
