### ISSUE TITLE
Missing Colored Force Fields

### ISSUE THREAD

**Issue by acd2001** [Interrupt/systemshock#220]
Latest source code has this bug:
![immagine1](https://user-images.githubusercontent.com/43091220/45987408-9517c300-c071-11e8-90ba-90d76b470be8.JPG)
![immagine2](https://user-images.githubusercontent.com/43091220/45987412-9b0da400-c071-11e8-8383-a64e1b17a0ae.JPG)
[savgam01.zip](https://github.com/Interrupt/systemshock/files/2413443/savgam01.zip)

**Comment by donnierussellii** [comment]
Sorry about that. I broke this trying to fix a crash. Fix in my PR #222.

**Comment by donnierussellii** [comment]
I remember this same bug early in the public beta of Night Dive's source port.
