### ISSUE TITLE
cheat level jump crashes systemshock

### ISSUE THREAD

**Issue by acd2001** [Interrupt/systemshock#224]
pressing repeteadly ctrl-4 or ctrl-5, shockolate crash with segmentation fault

**Comment by donnierussellii** [comment]
From new game, pressing key repeatedly until crash:

ctrl+4:

Program received signal SIGSEGV, Segmentation fault.
0x004dfd78 in g3_draw_cline ()         [I've seen crashes here before]
(gdb) backtrace
#0  0x004dfd78 in g3_draw_cline ()
#1  0x0040bd02 in _fr_draw_wire_cpoly_4 ()
#2  0x0040c495 in _fr_cspace_wire_int_wall ()
#3  0x0040eeba in fr_draw_tile ()
#4  0x00497b5d in draw_dir_dir ()
#5  0x00497f2f in fr_pipe_go_3 ()
#6  0x00496a3a in fr_rend ()
#7  0x004574fb in render_run ()
#8  0x004116f9 in game_loop ()
...

ctrl+5

Program received signal SIGSEGV, Segmentation fault.
0x0045a10b in load_current_map ()
(gdb) backtrace
#0  0x0045a10b in load_current_map ()
#1  0x0049df75 in load_level_from_file ()
#2  0x00458b4e in go_to_different_level ()
#3  0x004178c3 in toggle_down_level_func ()
...

**Comment by donnierussellii** [comment]
Fix in my PR #230
