### ISSUE TITLE
RF 07 Skorpion Rifle crash

### ISSUE THREAD

**Issue by acd2001** [Interrupt/systemshock#225]
Start a new game, press ctrl-2 for ammo cheat, seleck RF07 Skorpion Rifle and shot around screen long pressing mouse button and shockolate crash with:

Thread 1 received signal SIGSEGV, Segmentation fault.
fr_get_real (cur_fr=0x22ef4c0, x=73, y=-14)
    at c:/systemshock-master/src/GameSrc/frutil.c:115
115         col = (int)(*((cur_fr->draw_canvas.bm.bits) + (y * cur_fr->draw_canv
as.bm.row) + (x)));

**Comment by acd2001** [comment]
Crash happens with various weapons.
Just shoot near hud border.
![immagine1](https://user-images.githubusercontent.com/43091220/46028741-ac969080-c0f1-11e8-8a67-d89dc294a027.jpg)

**Comment by donnierussellii** [comment]
This code reads a pixel at x,y and returns the object associated with that color. Looks like x,y is going out of bounds. I will make sure by printf'ing the coords.

These kinds of things wouldn't crash DOS so went unnoticed. Just imagine all the passwords you could read without memory protection!
