### ISSUE TITLE
[Feature Missing] Fade effects in videos

### ISSUE THREAD

**Issue by acd2001** [Interrupt/systemshock#227]
Some videos are missing of fade effects at the end.
Specifically videos of intro and death scene.

Moreover, in the new game screen, the vital signs refresh 
are very slow (if compared with SSHOCK.EXE).

**Comment by Interrupt** [comment]
Should all cutscenes fade out at the end?

**Comment by donnierussellii** [comment]
At the ends of cutscenes as they currently are, there is some audio cut off at the end. I have a PR ready that pauses then fades out to synchronize with the end of audio.

Fading out the win cutscene looks like that's the way it's supposed to be. Looks nice to me.

For the intro cs, it looks like it should pause and fade out the same as the win cs.

And for the death cs, it looks odd to stop the blinking light animation during the pause and fade out. Maybe this should be the exception. But otoh it does seem to end too abruptly.

**Comment by donnierussellii** [comment]
Addressed pause & fade in my PR #231
