### ISSUE TITLE
[Feature Request] Single click item pickup

### ISSUE THREAD

**Issue by voodoo47** [Interrupt/systemshock#239]
Having to drag stuff from the world or containers can get tiring - would be nice if items could be just one click auto picked right into the inventory, SS2 style (basically, instead of getting attached to the mouse pointer, they would pop right into the inventory). Fully optional, of course. This would also decrease the need to switch between use and shoot modes slightly, I consider this a good thing.

**Comment by donnierussellii** [comment]
I'll try implementing this with shift+click.
