### ISSUE TITLE
Needs a framerate limiter

### ISSUE THREAD

**Issue by Interrupt** [Interrupt/systemshock#24]
Right now the game runs as fast as it can, we should probably either try to VSYNC (via SDL OpengGL?) or limit the game loop so that it's not rendering at 800fps

**Comment by Lisoph** [comment]
Good idea, but make this optional. Some people prefer an unlimited frame rate.

**Comment by Interrupt** [comment]
A good solution here might be to use OpenGL to do the final call to draw pixels to the screen from the SDL surface, that way we could turn on VSync and let GPU hardware manage things for us.
