### ISSUE TITLE
Travis CI is currently failing at build SDL_mixer

### ISSUE THREAD

**Issue by donnierussellii** [Interrupt/systemshock#243]

**Comment by Manuel-K** [comment]
The git clone is too shallow. 

https://github.com/Interrupt/systemshock/blob/master/osx-linux/install_32bit_sdl.sh#L20

**Comment by Manuel-K** [comment]
I think it would be a better choice to use the last stable release and apply https://github.com/SDL-mirror/SDL_mixer/commit/7cad09d4d479df2b21b3e489f8e155bdf8254fd4 as a patch. 

We do not need any other change made since the release of 2.0.2.

**Comment by Interrupt** [comment]
That is probably a better path forward until there is a new release. Do you know the git magic to make a patch out of that commit to apply it?

**Comment by Manuel-K** [comment]
On github you can add `.patch` to the commit url to get a patch file, e.g. https://github.com/SDL-mirror/SDL_mixer/commit/7cad09d4d479df2b21b3e489f8e155bdf8254fd4.patch
