### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by acd2001** [Interrupt/systemshock#265]
Load savegame and double click Rail Gun weapon.
Shockolate crash with memory error : Not enough cache memory to load bitmap.
See picture. I attach savegame too.

![immagine](https://user-images.githubusercontent.com/43091220/47270684-bb952500-d56f-11e8-8e58-c1a0e189b57b.JPG)
[savgam02.zip](https://github.com/Interrupt/systemshock/files/2499475/savgam02.zip)

**Comment by donnierussellii** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x00468c3b in res_bm_height ()
(gdb) backtrace
#0  0x00468c3b in res_bm_height ()
#1  0x00426873 in draw_ammo_button ()
#2  0x00426b83 in mfd_weapon_draw_ammo_buttons ()
#3  0x004267a1 in mfd_weapon_expose_projectile ()
#4  0x004266ae in mfd_weapon_expose ()
#5  0x004418f6 in mfd_update_current_slot ()
#6  0x0044179f in mfd_update ()
#7  0x00411ae8 in game_loop ()
#8  0x00425bd7 in mainloop ()
#9  0x00401d67 in SDL_main ()
#10 0x00531947 in main_utf8 ()
#11 0x005319f8 in main_getcmdline ()
#12 0x00531afb in WinMain@16 ()
#13 0x0055e8b4 in main ()
