### ISSUE TITLE
Black screen instead of main menu unless CurrentGame.dat and at least one savgam.dat is present

### ISSUE THREAD

**Issue by voodoo47** [Interrupt/systemshock#270]
What the title says (using the freshly built 0.7 for windows). The mouse pointer is visible/movable and the music works, so the game is probably still running.

**Comment by HunterZ** [comment]
This no longer seems to be an issue?

**Comment by voodoo47** [comment]
still happening with the latest precompiled windows build (v0.7.5) for me.

**Comment by HunterZ** [comment]
Sorry, I mean with the latest master branch source code. Are you able to run this build as a test?
[systemshock.zip](https://github.com/Interrupt/systemshock/files/2974195/systemshock.zip)

**Comment by voodoo47** [comment]
same behavior with the build from the zip.

**Comment by HunterZ** [comment]
This is when running with no .dat files in the .exe folder?

Where did your resource files come from? I wonder if they're different from mine (latest SSEE on GOG).

**Comment by voodoo47** [comment]
aha, slight correction - looks like I only need one save file now (CurrentGame.dat will get created once I load it). resources were pulled from the dosbox/cd version (GOG).

**Comment by voodoo47** [comment]
anyway, closing for now, as I'm 99% sure this was caused by using improper resources.
