### ISSUE TITLE
libADLMIDI configuration: music sounds weird

### ISSUE THREAD

**Issue by markkurikola** [Interrupt/systemshock#277]
The situation right now is this: the music files play correctly enough, but the _instruments_ sound off. It sounds like Shockolate is using the SB16 instrument bank, which to many people (especially those familiar with SSEE's general MIDI instrumentation) isn't the correct sound of the songs.

**Comment by jpcima** [comment]
Are you looking for different timbres of Adlib FM sounds, or an entire style of synthesis entirely?
General MIDI can mean anything. Maybe you are expecting more hi-fi wavetable expander in software, like fluidsynth. From your question, I'm not exactly sure.

A thing may be to offer multiple configurable choices for music setup. Gzdoom offered this kind of choice: https://zdoom.org/wiki/Software_synthesizer
(it could have libADLMIDI, Fluidsynth, Sonivox EAS, system port for hardware expander, etc)

As @Wohlstand suggested previously, you could extract the XMI sequencer of libADLMIDI, and redirect the MIDI stream to the prefered synth backend.

**Comment by Wohlstand** [comment]
@jpcima , GZDoom's sequencer is also able to play XMIs but Idk how much accurate...
https://github.com/coelckers/gzdoom/blob/master/src/sound/midisources/midisource_xmi.cpp

**Comment by markkurikola** [comment]
Honestly, I have no idea what the actual root cause is 😂 Maybe the best I can offer is these two clips as comparison points:

[SB16 / how Shockolate sounds](https://www.youtube.com/watch?v=0yhmv0RK9qM&t=781)

[how SSEE sounds](https://www.youtube.com/watch?v=Jffl4PNT8JY&t=154)

**Comment by jpcima** [comment]
I have the Classic Edition and I found from inspecting the game folders.
It's a game for DOS, for which DOSBox provides emulation.
In `SOUND` folder we have, among things:
- *.OPL *.AD, the sound banks for OPL3/2 probably
- what may be music drivers of various sound interfaces (ADLIB, MPU401, MT32MPU, OPL3, SB16/PRO/AWE32)
- `GENMIDI/` and `SBLASTER/` have XMIs targeted at either (guess): General MIDI, or channel-limited Adlib

This computer hasn't EE on it, so I will redownload this one to give it a check.

**Comment by jpcima** [comment]
I ran Enhanced Edition on Wine. As I was able to see from logs of `WINEDEBUG+=winmm`, the music is playing on the Windows MIDI mapper.
On the ordinary user's computer, I expect this most likely to be the "Microsoft GS Wavetable Synth".

I suggest to provide fluidsynth with soundfont as alternative backend which is portable.
It's also permitted to offer as other backend WinMM as well, like the original has.

**Comment by mrikola** [comment]
I think it's safe to close this one.

**Comment by jpcima** [comment]
I don't know. Have you found the solution satisfying?
My code wasn't merged in the main tree yet.

**Comment by markkurikola** [comment]
I made https://github.com/Interrupt/systemshock/pull/280 on top of your solution, so yeah I did 😄

**Comment by jpcima** [comment]
Great :smile: 
It's a talkative commit log as I can see. Good luck, call me if you need

**Comment by markkurikola** [comment]
Yeah 😂 that's what happens when you have to go against a CI system in the dark and something just randomly fails to compile on there... 🤦‍♂️

**Comment by Wohlstand** [comment]
AppVeyor and Travis-CI are always a strong pain :rofl: 
Scroll down, and you'll see a very long chain of talkative commits: related to Travis-CI:
https://github.com/WohlSoft/PGE-Project/commits/master?before=73c128a4dc4f18a485dd9f592b186c4562a29a91+35
And here another fight versus AppVeyor: https://github.com/WohlSoft/PGE-Project/commits/master?after=73c128a4dc4f18a485dd9f592b186c4562a29a91+69
