### ISSUE TITLE
SystemShock assets version

### ISSUE THREAD

**Issue by Rugaliz** [Interrupt/systemshock#28]
HI
I thing you may have forgotten to specify the correct version of the "original" assets.
The game wont run if you use the assets from the classic version available on gog when you put them in the res/data folder accordingly. It only works with the Enhanced edition that has different map versions. Maybe this should be specified in the reademe ?

Cheers

**Comment by speachy** [comment]
It appeared to run okay with the assets off the original DOS System Shock CD-ROM.  Once I lowercased all of the filenames, anyway.

(Now I have no idea if the original DOS floppy version assets work, but I don't know why anyone would bother with those, unless they want to take advantage of the battery+first aid kit cheat or the lantern+shield+turbo booster cheat)

**Comment by Rugaliz** [comment]
Yes, i was referring to the versions available on GOG.com where you have the classic and enhanced versions. I dont have any other versions and i assumed people nowadays would be using the gog versions.

**Comment by winterheart** [comment]
OK, there little confusion about versions and editions. Here little info what supported and not:

| Edition | Release Date | Support |
|----------|-------------------|------------|
| SS Floppy | Sen 24, 1994 | **No** (old version of maps)
| SS CD | Dec, 1995  | **Yes**
| SS GOG Enhanced Edition | 2015  | **Yes** (effectively this is SS CD)
| SS for PC-98 (Japanese version) | May 24, 1996 | **Unknown** (not tested)
| SS for MacOS | Dec, 1995  | **No** (different data types)

**Comment by Interrupt** [comment]
There’s some commented out code around converting from older map versions, maybe we should get that working again to fix the floppy disk assets not loading?

**Comment by Interrupt** [comment]
Added a note around this in the github README file for now, it would be nice to get those older archives loading someday though
