### ISSUE TITLE
Implementing Logger framework

### ISSUE THREAD

**Issue by winterheart** [Interrupt/systemshock#37]
Current logging functionality taken partly from LG/dbg.c, partly - simple printf(). I think there should be better solution.
I checked https://github.com/rxi/log.c and it works pretty well, but maybe someone give better frameworks.
Here some requirements:
* Code should be C99 compatible
* License should be GPL-3 compatible
* No external file configuration (only in-code, we could implement own configuration file)

**Comment by Interrupt** [comment]
An in game console would be awesome too, if we could tie it into stdout / whatever logging framework we pick up.

**Comment by Interrupt** [comment]
I'm okay with using that `rxi/log.c` library to start with, we should probably implement some logging defines to sit in front of it so that people don't call it directly to make it easier to swap out the logging implementation.
