### ISSUE TITLE
adding libxmp for better midi support

### ISSUE THREAD

**Issue by joinlaw** [Interrupt/systemshock#38]
take a look at

https://github.com/cmatsuoka/libxmp

http://xmp.sourceforge.net/

https://github.com/cmatsuoka/xmp-cli

**Comment by Interrupt** [comment]
Would this be able to play the XMI midi files? WildMidi might be a better choice.

**Comment by winterheart** [comment]
Related to #14, but as I can see libxmp is not supporting MIDI or XMI format.

**Comment by joinlaw** [comment]
you right!
how did i forget! libxmp for tracker formats & wildmidi for midi!
keep going
thank you!
close the issue
