### ISSUE TITLE
What datafiles does the engine need exactly?

### ISSUE THREAD

**Issue by vanfanel** [Interrupt/systemshock#385]
Hi all,

I have just built Shockolate from sources for the first time, on GNU/Linux, SDL2.
The problem is that I don't know what files does it need in res/data exactly.
Most other engines have those files listed in the docs, and what versions of the game provides them, but I have tried copying over the EE data files and the CDROM data files, and I am always missing a list of them.
I somewhat got the game to boot by mixing datafiles from different versions, but all I got was a black screen at game start.

So, any file list, please?

Thanks!

**Comment by Oreo639** [comment]
You need to copy the following files:
`<steamdir>/steamapps/common/SS1/DATA` to `<bindir>/res/data`
`<steamdir>/steamapps/common/SS1/GEN` to `<bindir>/res/gen`
`<steamdir>/steamapps/common/SS1/MUSIC` to `<bindir>/res/music`

**Comment by vanfanel** [comment]
@Oreo639 Thanks, but I have the GOG version, I don't use that Steam thing at all.

**Comment by Oreo639** [comment]
Should be the same thing, just make sure it is the files from the classic CD version an not the sourceport.

**Comment by vanfanel** [comment]
@Oreo639 Isn't the GOG "Enhanced Edition" supported too?

**Comment by billbeans** [comment]
This still needs some clarification. I have the cdrom and there is no 'res' folder. I have installed it with Dosbox and it made a SSHOCK folder with DATA, GEN, and SOUND folders inside. The GEN folder is empty, and I think there are more assets on the disk, which I extracted.

**Comment by BigCojones** [comment]
This for sure needs more clarification.  I äm trying to run the Enhanced Edition through Steam, but there isn't any folders like the ones described.
