### ISSUE TITLE
Hover-tooltips are wrong size when reloading a savegame made with non-default resolution

### ISSUE THREAD

**Issue by JPLeBreton** [Interrupt/systemshock#44]
steps to reproduce:
1. start a new game
2. set the resolution to 1024x768
3. save the game
4. relaunch shockolate
5. load that saved game
6. hover the mouse over one of the buttons that has a tooltip, eg the lower side tabs for automap etc
7. observe: the tooltips are still 640x480-sized

Setting the resolution to 640 and back fixes this, but that must be done on every new launch so that's more of a workaround.

**Comment by Interrupt** [comment]
Fixed in commit https://github.com/Interrupt/systemshock/commit/6bd97bc4d1d5b30e437cce881684076406ddd9b0
