### ISSUE TITLE
Object spawns are broken when starting a new game

### ISSUE THREAD

**Issue by JPLeBreton** [Interrupt/systemshock#45]
steps to repro:
1. launch shockolate
2. start a new game with any difficulty settings
3. observe: left door in first room starts open, there's a mutant inside it, and none of the stuff you need to get through the door out of this room is there.

I tried wiping my save data just in case this was related, no change in behavior.

**Comment by Interrupt** [comment]
Not seeing this behavior when running clean builds on OSX or Linux, so this is a strange one. It sounds like a similar issue to your 'everything is a phone' bug that popped up once. That fixed itself when you sorted out SDL, right? Is CMake finding the wrong SDL again?

**Comment by JPLeBreton** [comment]
I'm seeing visuals and hearing sound, so it must be using the right SDL and SDL_mixer right?
How different is the code path for loading into a new game from the menu versus starting a new game via launching before the menu code came in? (Which, admittedly in my case, was long enough ago that many other things about the codebase were different.)

**Comment by Interrupt** [comment]
Starting a game via the main menu should just delay the call to `go_and_start_the_game_already` which starts the game up, that used to be the first thing that was done but now we start in the main menu instead.

**Comment by JPLeBreton** [comment]
Just to have a paper trail here, as we discussed this happens due to case-insensitivity of the code that copies res/data/archive.dat to create the new current game save data.

**Comment by Interrupt** [comment]
Opened a new Issue to deal with this: https://github.com/Interrupt/systemshock/issues/50
