### ISSUE TITLE
Credits screen code is missing

### ISSUE THREAD

**Issue by Interrupt** [Interrupt/systemshock#48]
The code to run the original credits screen appears to have gone AWOL. There's references to a header file called "scrntext.h" that probably handled this stuff but that's missing as well.

**Comment by winterheart** [comment]
Credit strings placed in 0x087C (0..177) ResId of cybstring.res, referenced as `RES_credits` in engine.

**Comment by Interrupt** [comment]
The credits screen also doesn't show after beating Shodan, instead the game quits totally.

**Comment by Interrupt** [comment]
Fixed the credits screen not showing after Shodan is beaten in 21a079b6e510c99b6711014a9327dd3c11b9ac60

**Comment by donnierussellii** [comment]
Reverse-engineered credits display in my PR #179.

**Comment by Interrupt** [comment]
Nice! This can be closed now.
