### ISSUE TITLE
Shipping Builds / CI

### ISSUE THREAD

**Issue by Interrupt** [Interrupt/systemshock#51]
This might be stable enough now to start regularly cutting builds on the major platforms (Windows/Linux/OSX)

There are some open questions though:
- How should we do this? Manually or through some kind of CI system?
- How often should these be made: weekly, monthly?

**Comment by AcceptableSpare** [comment]
As a user I'm mostly used to getting stuff from travis / appveyor auto builds. It's really up to you though, If having more stable builds works better for you then just do that. Though I'm itching to try this out with my system shock cd like right now :>

**Comment by winterheart** [comment]
As far as I know Travis support uploading of tagged commits back to Github. So here draft of workflow:

* Run build tests on every commit, with system and local SDL2 libraries.
* On every tagged commit (ie version milestone) build Release version and attach it to Github tag as zip, rpm, deb etc.
* Run nightly build on every week, save them in Travis locally.

**Comment by mrikola** [comment]
I mentioned this to @Interrupt over Twitter DM but let's put it here as well: [AppVeyor](https://www.appveyor.com/) seems like a nice choice for the Windows CI. It seems to have out-of-the-box support for all the stuff needed for a Windows build, but I haven't made any actual attempts at configuring it yet.

**Comment by Interrupt** [comment]
Thanks to work done by @Laastine and @mrikola we have CI builds happening on checkins, and release deployments that run on tags. Our first fully automated release is here: https://github.com/Interrupt/systemshock/releases/tag/v.0.5.10.2
