### ISSUE TITLE
Slowdown when touching energy drain mines on Deck 8

### ISSUE THREAD

**Issue by JPLeBreton** [Interrupt/systemshock#71]
steps to reproduce:
1. open the attached savegame
2. walk forward towards the floating mines and let yourself fall
3. observe: framerate slows down significantly as you intersect with the mines

This is a comparatively very minor issue, as it's not necessary to ever do this if you know the correct solution to this deck (ie extending the bridge so you can walk across the space the mines are covering). It's possible this behavior also exists in the vanilla DOS executable, Shockolate saves aren't vanilla-compatible so I can't easily test that.

[jp_save_slowdown_mines.zip](https://github.com/Interrupt/systemshock/files/2156279/jp_save_slowdown_mines.zip)

**Comment by AcceptableSpare** [comment]
Were there any on deck 9?  seem to recall playing it on my laptop and it causing a crash in game for the ms dos cd-rom version. I think I might still have a save on my old laptop

**Comment by JPLeBreton** [comment]
I just finished deck 9 and I don't recall seeing any there.

**Comment by AcceptableSpare** [comment]
The only save i have is on the reactor mission. You could probably just use the debug code to skip all of it
[SAVGAM01.zip](https://github.com/Interrupt/systemshock/files/2161475/SAVGAM01.zip)

**Comment by mrikola** [comment]
I think it has to do with the energy mines trying to push you back. Falling into a mine makes it push you back up, but less than how much gravity would pull you down. Now, on every frame until you fall back out of range, you hit the radius of the energy mine, which causes the game to attempt playing a sample.. and to fail once the maximum number of samples is playing. I got upwards of 100 "SDL_Mixer: Failed to play sample" notifications from trying this.

**Comment by inguin** [comment]
The sample error messages can easily be fixed by only starting the sample if it's not already playing: Change `physics.c:1553` as follows:

```
if (!digi_fx_playing(SFX_ENERGY_DRAIN, NULL))
    play_digi_fx(SFX_ENERGY_DRAIN, 1);
```

Touching the mine still slows your fall, but I guess that's intended.

**Comment by mrikola** [comment]
This looks good. Mind making a PR out of it, @inguin?
