### ISSUE TITLE
Progression blocker: final door to SHODAN fails to open when Isolinear Chipset installed

### ISSUE THREAD

**Issue by JPLeBreton** [Interrupt/systemshock#72]
steps to reproduce:
1. open the attached savegame
2. drag the "iso chipset" item from your general inventory into the "computer program entry" panel on the directly ahead of you
3. exit this room, go back into the main area and take a left
4. find the west wall of the central octagonal feature
5. observe: this wall should now be open to reveal the chamber with the game's final cyberspace terminal, but it is not.

See [this video](https://youtu.be/yQWqmVnuas4?t=43m23s) (timestamp 43:23) for what should happen.

For what it's worth the computer speech that follows inserting the chipset doesn't happen in the current build, but I'm guessing that that's simply due to digitized speech eg audio logs not working yet.

[jp_save_shodan_final_door.zip](https://github.com/Interrupt/systemshock/files/2156408/jp_save_shodan_final_door.zip)

**Comment by inguin** [comment]
Still seeing the same issue. Is this not fully fixed, or could my savegame be too old? I *think* I started this run on July 5, after this fix. Not sure, though.
