### ISSUE TITLE
SHODAN despawns in final battle?

### ISSUE THREAD

**Issue by mrikola** [Interrupt/systemshock#76]
I picked up JP Le Breton's Isolinear Chipset save game and walked into the final battle, but even after several attempts I can't manage to win. Part of me thinks the fight is timed based on frames you take (I feel like the screen fills up with pixels faster than the original) but I also definitely saw the SHODAN core despawn mid-fight... and that makes the fight literally unwinnable.

**Comment by Interrupt** [comment]
Is there some kind of timer in the last cyberspace level? I have also noticed that the pixelization effect happens way fast, wonder if they are linked together.

**Comment by JPLeBreton** [comment]
I'm seeing this too now. I phaser SHODAN a bunch, and at some point her sprite disappears. In its place I thought I saw - by that point the SHODAN face pixelation was starting to get heavy - a small light gray cube, like one of the data objects you pick up in cyberspace. However I was unable to pick it up or do much of anything else, and then 5-10 seconds later the pixelation death state overtook me. Haven't been able to do much besides this. I definitely haven't seen the credits roll yet.

**Comment by Interrupt** [comment]
This might be fixed after 0b15d3e1b4729bf7a4690ab19f53cd6dd9ff4e78

**Comment by mrikola** [comment]
Interesting. Now I was unceremoniously tossed to the command prompt 😆

**Comment by JPLeBreton** [comment]
Just tried latest and I *think* I successfully beat the game. I was right-clicking like a fiend to deal damage to SHODAN, then I very very briefly (like, for one frame) saw what I think was the credits screen, then popped back to the main menu. So this is probably the intended victory flow, just without the finale cutscene playing and with the credits screen instantly (thus accidentally, if you're hammering a button) skippable. It appears that the issue itself, "SHODAN despawns", is fixed.

Once video cutscenes are working, we can see if the "immediately accidentally skip coming out of gameplay" behavior still happens and fix if needed, by eg ignoring the first second or two of input before allowing skip.

**Comment by mrikola** [comment]
Okay, I get the same behavior now. I think I was actually winning the fight with the old code intact when the "thrown to command prompt" behavior happened. So for now I think we can close this one, and consider the missing ending video and scoring sequence a different set of issues.
