### ISSUE TITLE
Automatic detection of locally built SDL components is wonky on Fedora

### ISSUE THREAD

**Issue by StrayLightning** [Interrupt/systemshock#79]
I had problems with DBUS errors until I RTFM and realised I needed to build SDL2 components manually.  It looks like there's automatic detection of these under externals/findsdl2-cmake/, but it always seems to pick the system-installed headers and libraries first.  I needed to explicitly specify the locations of the locally built ones.

The first thing I note is that the set(CMAKE_MODULE_PATH ...) occurs after find_package(SDL2) which looked odd.

This is what I did to successfully build on my Fedora 28 x86_64:

    sudo dnf install glibc-devel.i686
    ./build_deps.sh
    SDL2_DIR=build_ext/built_sdl SDL2_MIXER_DIR=build_ext/built_sdl_mixer cmake .
    make -j8

(Edited to make it clear that I can build successfully by explicitly specifying local SDL2 locations.)

**Comment by inguin** [comment]
I'm on Fedora 27, and System Shock builds just fine with the includes from the system `SDL2-devel.i686` and `SDL2_mixer-devel.i686` packages.
I _do_ need a locally-built version of SDL2_mixer (the official 2.0.2 release segfaults when trying to play a VOC file), but for that I just copied `libSDL2_mixer-2.0.so.0` into the local directory and run with `LD_LIBRARY_PATH=. ./systemshock` so the dynamic linker picks it up before the system version.

**Comment by Interrupt** [comment]
PR https://github.com/Interrupt/systemshock/pull/84 should make the detection of SDL_mixer a bit more automatic when it comes to the local builds.

**Comment by StrayLightning** [comment]
I tried PR#84 with: 

git fetch https://github.com/Interrupt/systemshock.git pull/84/head:pr84
git checkout pr84

CMake reported better than before, but it's still picking up the system SDL includes, and it looks like it would try to pick up the 64-bit library from the system:

-- Found SDL2_MIXER: /home/[...]/systemshock-interrupt/build_ext/built_sdl_mixer/lib/libSDL2_mixer.so  
-- Found SDL2 Include:/usr/include/SDL2 Library:-L/usr/lib64  -lSDL2
-- Found SDL2_Mixer Include:/home/[...]/systemshock-interrupt/build_ext/built_sdl_mixer/include/SDL2 Library:/home/[...]/systemshock-interrupt/build_ext/built_sdl_mixer/lib/libSDL2_mixer.so

The build then fails because I don't have SDL2-devel.i686 installed:

/usr/include/SDL2/SDL_config.h:42:10: fatal error: SDL_config-i386.h: No such file or directory
 #include "SDL_config-i386.h"

**Comment by winterheart** [comment]
Use `cmake -DSDL2_DIR=/usr/lib32/cmake/SDL2 <path to sources>`.

**Comment by StrayLightning** [comment]
Thanks @winterheart.  I have edited my original Issue text to be explicit that I could build by specifying the local SDL2 locations.

**Comment by Interrupt** [comment]
@StrayLightning I updated PR#84 to be better about finding the locally built SDL2 over the system built one, want to give it a shot?

**Comment by StrayLightning** [comment]
@Interrupt -- That worked great:

$ cmake .
[...]
-- Found SDL2 Include:/home/[...]/systemshock-interrupt/build_ext/built_sdl/include/SDL2 Library:-L/home/[...]/systemshock-interrupt/build_ext/built_sdl/lib **-Wl,-rpath,/home/[...]/systemshock-interrupt/build_ext/built_sdl/lib** -Wl,--enable-new-dtags -lSDL2
-- Found SDL2_Mixer Include:/home/[...]/systemshock-interrupt/build_ext/built_sdl_mixer/include/SDL2 Library:/home/[...]/systemshock-interrupt/build_ext/built_sdl_mixer/lib/libSDL2_mixer.so
[...]

**Comment by Interrupt** [comment]
I think this is fixed now, closing.
