### ISSUE TITLE
Crash running latest with adlmidi-xmi branch

### ISSUE THREAD

**Issue by JPLeBreton** [Interrupt/systemshock#94]
steps to repro:
1. sync and build adlmidi-xmi branch
2. start a new game with default difficulty settings
3. clear out the first area before the keypad door (the 3 bots and 2 cameras)
4. walk over to the healing bed from wherever you are - in my repros i don't think the healing bed had anything to do with the crash, it was just where i was headed to heal myself after killing the robots

Debugger told me the crash was on line 1409 of `midi_sequencer_impl.hpp`, the first line of BW_MidiSequencer.

Last few lines of my log before the crash, in case they're useful:
```
14:15:47 DEBUG resacc.c:113: ResUnlock: id $36 already unlocked
14:15:47 DEBUG mlimbs.c:276: AIL callback 119 triggered, running music AI
14:15:47 DEBUG mlimbs.c:149: snd_end_sequence 2
14:15:47 DEBUG mlimbs.c:1049: mlimbs_punt_piece 4 on 1
14:15:47 DEBUG mlimbs.c:412: _mlimbs_clear_uid
14:15:47 DEBUG mlimbs.c:149: snd_end_sequence 3
14:15:47 DEBUG mlimbs.c:1049: mlimbs_punt_piece 18 on 2
14:15:47 DEBUG mlimbs.c:412: _mlimbs_clear_uid
14:15:47 DEBUG mlimbs.c:397: _mlimbs_clear_req
14:15:47 DEBUG mlimbs.c:1363: New piece 5
14:15:47 DEBUG mlimbs.c:937: mlimbs_play_piece 5, times 4
14:15:47 DEBUG mlimbs.c:103: snd_sequence_play: 6 res/sound/genmidi/thm1.xmi
14:15:47 DEBUG mlimbs.c:125: Playing track 6 on 2
14:15:47 DEBUG mlimbs.c:624: Unmute sequence 1 for piece 6
14:15:47 DEBUG mlimbs.c:624: Unmute sequence 1 for piece 6
14:15:47 DEBUG mlimbs.c:624: Unmute sequence 1 for piece 6
14:15:48 DEBUG musicai.c:349: mai_transition
14:15:48 DEBUG musicai.c:395: make_request 0 5
14:15:48 DEBUG musicai.c:395: make_request 1 16
Segmentation fault (core dumped)
```

**Comment by Interrupt** [comment]
The things I'm doing to the the ADL library in getting it to loop the multiple XMIDI sequences here are probably far beyond what that library is expecting for normal use. I'm creating multiple instances of the ADL player and mixing their output, but I should probably make a new sequencer instead that is smarter about handling loops so that there's just one sequencer running and not 8.
